
var trad = {
  "Ampersand":"Esperluette",
  "Angle bracket":"Chevron",
  "Anti-pattern":"Anti-patron",
  "API (Application Programming Interface)":"IPA (Interface de Programmation Applicative)",
  "Applet":"Appliquette",
  "ASLR":"Disposition Stochastique de l’espace d’adressage",
  "Assignation":"Affectation",
  "Back office":"Arrière-guichet",
  "Back-end service":"Service dorsal",
  "Backbone":"Réseau dorsal",
  "Backdoor":"Porte dérobée",
  "Backport":"Rétroportage",
  "Backslash":"Barre oblique inversée",
  "BBS (Bulletin Board System)":"Babillard électronique",
  "Beautifier":"Enjoliveur",
  "Benchmark":"Banc d’essai",
  "Big data":"Mégadonnées",
  "Big-endian":"Gros-boutiste" ,
  "Binding":"Reliage",
  "Bit (Binary digit)":"Chibi (Chiffre Binaire)",
  "Bloatware":"Boufficiel",
  "Blockchain":"DEEP (Dispositif d'Enregistrement Électronique partagé)",
  "Boot":"Amorçage",
  "Bootstrapping (compiler)":"Compilogénèse",
  "Bootstrapping (OS)":"Autoamorçage",
  "Bot":"Automate",
  "Branch merging":"Fusion de branches",
  "Browser":"Navigateur",
  "Brute force attack":"Attaque exhaustive",
  "Buffer":"Tampon",
  "Buffer overflow":"Dépassement de tampon",
  "Bug":"Bogue",
  "Bundle":"Colis",
  "Buzz":"Ramdam",
  "Buzzword":"Mot à la mode",
  "BYOD (Bring Your Own Device)":"AVEC (Apportez Votre Equipement personnel de Communication)",
  "Byte":"Octet",
  "Cache memory":"Antémémoire",
  "Call scam":"Appel piège",
  "Callback function":"Fonction de rappel",
  "Capitalization":"Majusculation",
  "Cascading Style Sheets (CSS)":"Feuilles de style en cascade",
  "CDROM":"Cédérom",
  "CEO Fraud":"Fraude au PDG",
  "Chatterbot":"Discutomate",
  "Checksum":"Somme de contrôle",
  "Cherry pick":"Picorage",
  "Chief Data Officer (CDO)":"Directeur/-trice des données (CDD)",
  "Chipset":"Jeu de puces",
  "Clickjacking":"Escrocliquerie",
  "Cloud computing":"Infonuagique",
  "Cluster":"Grappe",
  "Commit":"Atome de code",
  "Computer illiteracy":"Illectronisme",
  "Computer Science (CS)":"Science informatique",
  "Connection Pool":"Réserve de connexions",
  "Content Delivery Network (CDN)":"Réseau de Diffusion de Contenu (RDC). ",
  "Cookie":"Témoin de connexion",
  "Core dump":"Vidage de mémoire",
  "Crawler":"Butineur",
  "Crypto-currency":"Crypto-monnaie",
  "Cryptocoin":"Cybersou",
  "Cryptography":"Chiffrement",
  "Cryptoparty":"Chiffrofête",
  "Cybernaut":"Internaute",
  "Cybersquatting":"Accaparement de nom de domaine",
  "Dangling pointer":"Pointeur fou",
  "Dark net":"Internet clandestin",
  "Data scientist":"Expert·e en mégadonnées",
  "Database":"Base de données",
  "DDoS (Distributed Denial of Service)":"DSD (Déni de Service Distribué)",
  "Deadlock":"Interblocage",
  "Debugger":"Dévermineur",
  "Deep learning":"Apprentissage profond",
  "Deprecated":"Ringardisé" ,
  "Desktop":"Ordinateur de bureau",
  "Device":"Appareil",
  "Digital":"Numérique",
  "DoS (Denial of Service)":"Déni de Service",
  "Double word":"Trente-deuzet",
  "Download":"Téléchargement",
  "DRY (Don't Repeat Yourself)":"NTRP (Ne Te Répète Pas)",
  "E-mail":"Courriel",
  "Edit":"Modifier",
  "Empowerment":"Empouvoirement",
  "Encrypted":"Chiffré",
  "Endianness":"Boutisme",
  "Favicon":"Favorimage",
  "Fiber-optics":"Fribronique",
  "Firewall":"Pare-feu",
  "Firmware":"Micrologiciel",
  "Fix":"Correction",
  "Flag":"Fanion",
  "Flame":"Propos incendiaire",
  "Flood":"Matraquage",
  "Fork":"Scission",
  "FPGA (Field-Programmable Gate Array)":"CIPP (Circuit Intégré Prédiffusé Programmable)",
  "Framework":"Cadriciel",
  "Freeware":"Gratuiciel",
  "Front office":"Guichet",
  "Fuzzer":"Générateur d’anomalies",
  "Fuzzing":"Frelatage en masse",
  "GC (Garbage Collector)":"Ramasse-miettes, glaneur de cellule",
  "GDPR (General Data Protection Regulation)":"RGPD (Règlement Général sur la Protection des Données)",
  "Glue code":"Code ciment",
  "God object":"Objet omniscient",
  "Hacked":"Intrusé" ,
  "Hacker":"Fouineur",
  "Hackerspace":"Bidouillieu",
  "Hardening":"Durcissement",
  "Hardware":"Matériel",
  "Hash":"Condensat",
  "Hash table":"Tableau à adressage dispersé",
  "Hashtag":"Mot-croisillon",
  "Heap spray":"Pulvérisation du tas",
  "Home row":"Touche de repos",
  "Hub":"Concentrateur",
  "Hyperlink":"Hyperlien",
  "Infobox":"Infoboîte",
  "Initial Coin Offering (ICO)":"Crypto-émission de titres",
  "Instruction pipeline":"Instruoduc",
  "Internet of things":"Internet des objets",
  "JIT compiler":"Compilateur à la volée",
  "Laptop":"Ordinateur de giron",
  "Lazy evaluation":"Évaluation paresseuse",
  "Legacy":"Legs" ,
  "Lexing":"Analyse lexicale",
  "Library":"Bibliothèque",
  "Little-endian":"Petit-boutiste" ,
  "Log":"Journal" ,
  "Lolcat":"Chatmusant",
  "Looks Good To Me (LGTM)":"Ça Me Semble Bon (ÇMSB)" ,
  "Lurker":"Sous-Marineur",
  "Malware":"Maliciel",
  "Man-in-the-middle attack (MITM)":"Attaque de l’homme du milieu (HDM)",
  "Mapping":"Correspondance" ,
  "Mash-up":"Pot-pourriciel",
  "Merge-request":"Fusiodemande",
  "Middleware":"Intersticiel",
  "Monkey-in-the-middle attack":"Attaque du singe intercepteur",
  "Mouse jacking":"Vol à la souris",
  "Namespace":"Espace de noms",
  "Newsletter":"Infolettre",
  "NIH (Not Invented Here)":"PII (Pas Inventé Ici)",
  "Noob":"Novice",
  "Number sign":"Croisillon",
  "Obfuscation":"Noircissement de code",
  "Object pool":"Réserve d'objets",
  "Online chat":"Clavardage",
  "Overclocking":"Surcadençage",
  "Parsing":"Analyse syntaxique",
  "Pastebin":"Collodrôme",
  "Patch":"Rustine logicielle",
  "Perfect forward secrecy":"Confidentialité persistante",
  "Pharming":"Devoiement",
  "Phishing":"Hameçonnage",
  "Phishing attack":"Attaque par filoutage",
  "Pipeline":"Bitoduc",
  "Placeholder":"Marque substitutive",
  "Plugin":"Greffon",
  "Pod":"Gousse",
  "Podcasting":"Balladodiffusion",
  "Polling":"Attente active",
  "Polyfill":"Prothèse d'émulation",
  "Pool":"Réserve",
  "Pop-up":"Fenêtre ventouse",
  "Program counter":"Compteur ordinal",
  "Proxy":"Mandataire",
  "Pull-request":"Demande de hissage",
  "Ransomware":"Rançongiciel" ,
  "Rebase":"Greffe",
  "Refactoring":"Réusinage",
  "REPL (Read–Eval–Print Loop)":"BLEA (Boucle de Lecture, Evaluation et Affichage)",
  "Repository":"Dépôt",
  "Responsive":"Adaptatif" ,
  "REST (REpresentational State Transfer)":"REPOS (Représentation d'État Partagée par des Objets Situés)",
  "Return oriented programming":"Exploitation focalisée sur le retour",
  "Revenge porn":"Pornodivulgation",
  "Reverse proxy":"Mandataire inverse",
  "Reverse-engineering":"Ingénierie à rebours",
  "Rollback":"Rétropédalage",
  "Rolling release":"Publication continue",
  "ROM (Read-Only Memory)":"Mémoire morte",
  "RTFM (Read The Fucking Manual)":"LPDM (Lis le Putain De Manuel)",
  "Scale":"Passe à l’échelle",
  "Scaling":"Passage à l’échelle",
  "Selfie":"Egoportrait",
  "Shareware":"Partagiciel",
  "Shell":"Interprète de commandes",
  "Shell code":"Code encoquillé",
  "Slash":"Barre oblique",
  "Smart grid":"Grille maligne",
  "Smartphone":"Malinphone",
  "Smiley":"Émoticône",
  "Sniffer":"Renifleur",
  "SOAP (Simple Object Access Protocol)":"SAVON (Simple Accès Vers Objets Nuageux)",
  "SoC (System-on-Chip)":"Puce-système",
  "Software":"Logiciel",
  "Solver":"Solveur",
  "Spam":"Polluriel, pourriel",
  "Spammer":"Arroseur publicitaire",
  "Spinlock":"Tourniquet",
  "Spyware":"Espiogiciel",
  "Stack cookie":"Biscuit de pile",
  "Stack overflow":"Dépassement de pile",
  "Stand-up meeting":"Réunion debout",
  "Stash":"Remiser",
  "Switch":"Commutateur",
  "Tablet":"Planchette (tactile, digitale)",
  "Tag":"Étiquette",
  "Tainting analysis":"Contaminanalyse",
  "Thread":"Fil d'exécution",
  "Thread pool":"Réserve de fils d'exécution",
  "Thumbnail":"Imagette",
  "TIL (Today I Learnt)":"AJA (Aujourd’hui J’ai Appris)",
  "TL;DR (Too Long; Didn't Read)" :"TL;PL (Trop Long; Pas Lu)",
  "deface":"Défigurer",
  "reverse":"Détricoter",
  "spoil":"Divulgâcher",
  "TODO":"YAKA",
  "Touchpad":"Pavé tactile",
  "Trackball":"Boule de commande",
  "Tuning":"Bolidage",
  "Tutorial":"Didacticiel",
  "Tweet":"Gazouillis",
  "Typosquatting":"Faute de frappe opportuniste",
  "Underscore":"Sous-tiret",
  "Upload":"Téléversement",
  "URL":"Adresse réticulaire",
  "USB key":"Mémorette",
  "User Interface (UI)":"Interface Homme-Machine (IHM)",
  "Verbose":"Volubile",
  "Version control system":"Logiciel de gestion de versions",
  "Volunteer computing":"Calcul bénévole",
  "Walled garden":"Jardin secret, communauté prison",
  "Watchdog":"Chien de garde",
  "Web":"Toile",
  "Web cache":"Cache-toile",
  "Webcam":"Cybercaméra",
  "Webmail":"Portail de messagerie",
  "Webmaster":"Webmestre",
  "Wildcard":"Joker",
  "Workaround":"Contournement",
  "Wrapper":"Enrobeur",
  "XSS (Cross Site Scripting)":"ICID (Injection de Code Indirect à Distance)",
}

function traduction(){
  var txt = document.getElementById("txt").value;
  var txtTrad = [];
  var res = txt.split(" ");

  res.forEach((i) => {
    if(trad[i]){
      txtTrad.push(trad[i])
    }else{
      txtTrad.push(i)
    }
  });
  txtTrad = txtTrad.join(' ');

  var e = document.getElementById('txtTrad');
  e.innerHTML = txtTrad;
}
